# Generated by Django 4.0.4 on 2023-06-06 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_login_password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=30, unique=True)),
                ('company_login_password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_work_at', models.TimeField(blank=True, null=True)),
                ('finish_work_at', models.TimeField(blank=True, null=True)),
                ('start_break_at', models.TimeField(blank=True, null=True)),
                ('finish_break_at', models.TimeField(blank=True, null=True)),
                ('start_overwork_at', models.TimeField(blank=True, null=True)),
                ('finish_overwork_at', models.TimeField(blank=True, null=True)),
                ('workplace', models.CharField(choices=[('OFFICE', 'オフィス'), ('HOME', '在宅'), ('OTHERS', 'その他')], default='OFFICE', max_length=10)),
                ('work_contents', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidLeaveRecord',
            fields=[
                ('paid_leave_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_leave_date', models.DateField()),
                ('work_type', models.CharField(max_length=30)),
                ('paid_leave_reason', models.CharField(max_length=50)),
                ('requested_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'リクエスト済み'), ('CONFIRMED', '承認済み'), ('REJECTED', '拒否済み')], default='REQUESTED', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidLeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('max_paid_leave_days', models.FloatField()),
                ('used_paid_leave_days', models.FloatField()),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_type', models.CharField(choices=[('WORKDAY', '平日'), ('DAY_OFF', '休日'), ('HOLIDAY', '祝日'), ('ALL_DAY_LEAVE', '全休'), ('MORNING_LEAVE', '午前休'), ('AFTERNOON_LEAVE', '午後休')], default='WORKDAY', max_length=20)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='workrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'work_date'), name='unique_work_record'),
        ),
        migrations.AddConstraint(
            model_name='paidleaverecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'paid_leave_date', 'status'), name='unique_paid_leave_record'),
        ),
        migrations.AddConstraint(
            model_name='paidleaveday',
            constraint=models.UniqueConstraint(fields=('user_id', 'year'), name='unique_paid_leave_days'),
        ),
        migrations.AddConstraint(
            model_name='paidleave',
            constraint=models.UniqueConstraint(fields=('user_id', 'date'), name='unique_paid_leave'),
        ),
    ]
