# Generated by Django 4.0.4 on 2023-06-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_login_password',
        ),
    ]
