# Generated by Django 4.0.4 on 2023-06-12 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 17, 42, 1, 948007, tzinfo=utc), help_text='招待URLの有効期限です。デフォルトは1日です。'),
        ),
    ]
