# Generated by Django 4.0.4 on 2023-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workrecord_finish_break_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'work_date'), name='unique_work_record'),
        ),
    ]
