# Generated by Django 4.0.4 on 2023-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workrecord_unique_work_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='work_date',
            field=models.DateField(),
        ),
    ]
