# Generated by Django 4.0.4 on 2023-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_workrecord_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paidleaverecord',
            name='paid_leave_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('company_name', 'company_email'), name='unique_company'),
        ),
        migrations.AddConstraint(
            model_name='paidleave',
            constraint=models.UniqueConstraint(fields=('user_id', 'date'), name='unique_paid_leave'),
        ),
        migrations.AddConstraint(
            model_name='paidleavedays',
            constraint=models.UniqueConstraint(fields=('user_id', 'year'), name='unique_paid_leave_days'),
        ),
        migrations.AddConstraint(
            model_name='paidleaverecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'paid_leave_date', 'status'), name='unique_paid_leave_record'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('company_id', 'user_email'), name='unique_user'),
        ),
    ]
