# Generated by Django 4.0.4 on 2023-06-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaidLeaveDays',
            new_name='PaidLeaveDay',
        ),
    ]
