# Generated by Django 4.0.4 on 2023-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_paidleavedays_paidleaveday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
