# Generated by Django 4.0.4 on 2023-06-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_company_unique_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidleave',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='paidleave',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paidleaveday',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='paidleaveday',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paidleaverecord',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='paidleaverecord',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='workrecord',
            old_name='user_id',
            new_name='user',
        ),
    ]
