version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_BACKEND_PORT}:${CONTAINER_BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src
    env_file:
      - ./backend/.env
    command: python manage.py runserver ${CONTAINER_BACKEND_IP}:${CONTAINER_BACKEND_PORT}
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_FRONTEND_PORT}:${CONTAINER_FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src
    depends_on:
      - backend
    command: npm run dev
